// This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++, C#, and Java: http://www.viva64.com
// This file was auto-generated by ML.NET Model Builder. 

namespace NetMlDemo;

public partial class SentimentModel
{
	/// <summary>
	/// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
	/// </summary>
	/// <param name="mlContext"></param>
	/// <param name="trainData"></param>
	/// <returns></returns>
	public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
	{
		IEstimator<ITransformer> pipeline = BuildPipeline(mlContext);
		ITransformer model = pipeline.Fit(trainData);

		return model;
	}

	/// <summary>
	/// build the pipeline that is used from model builder. Use this function to retrain model.
	/// </summary>
	/// <param name="mlContext"></param>
	/// <returns></returns>
	public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
	{
		// Data process configuration with pipeline data transformations
		EstimatorChain<KeyToValueMappingTransformer> pipeline = mlContext.Transforms.Text.FeaturizeText(inputColumnName: @"col0", outputColumnName: @"col0")
			.Append(mlContext.Transforms.Concatenate(@"Features", @"col0"))
			.Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: @"col1", inputColumnName: @"col1"))
			.Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))
			.Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(new LbfgsMaximumEntropyMulticlassTrainer.Options { L1Regularization = 0.03403583F, L2Regularization = 1.380913F, LabelColumnName = @"col1", FeatureColumnName = @"Features" }))
			.Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName: @"PredictedLabel", inputColumnName: @"PredictedLabel"));

		return pipeline;
	}
}