name: Branch Main Build

on:
  push:
    branches:
      - main
    paths:
      - '**.csproj'
      - '**.razor'
      - '**.cs'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
  
      - name: Setup Nuget Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Install dependencies
        run: nuget restore HowToDoIt.sln

      - name: Build app for Debug Any CPU
        run: msbuild HowToDoIt.sln -t:rebuild -verbosity:quiet -property:Configuration=Debug -property:Platform="Any CPU"
      
      - name: Build app for Release Any CPU
        run: msbuild HowToDoIt.sln -t:rebuild -verbosity:quiet -property:Configuration=Release -property:Platform="Any CPU"
